version: '3.8'
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CLEARDB_DATABASE_URL=${CLEARDB_DATABASE_URL}
        - NODE_ENV=${NODE_ENV}
        - HOST=${HOST}
        - PORT=${PORT}
        - CACHE_VIEWS=${CACHE_VIEWS}
        - SESSION_DRIVER=${SESSION_DRIVER}
        - DRIVE_DISK=${DRIVE_DISK}
        - APP_KEY=${APP_KEY}
        - NODE-${NODE}
        - DB_CONNECTION=${DB_CONNECTION}
        - MYSQL_HOST=${MYSQL_HOST}
        - MYSQL_PORT=${MYSQL_PORT}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DB_NAME=${MYSQL_DB_NAME}
        - FRONT_URL=${FRONT_URL}
        - FRONT_ADMIN_URL=${FRONT_ADMIN_URL}
        - REDIS_CONNECTION=local
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_PORT=${REDIS_PORT}
        - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 8000:8000
    env_file:
      - .env
 
  database-mext-mysql:
    container_name: db-container
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'mext'
      MYSQL_USER: 'mext'
      MYSQL_PASSWORD: 'mextmysql'
      MYSQL_ROOT_PASSWORD: 'mextmysql'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  mext_redis:
    image: redis:alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'


volumes:
  my-db:
    driver: local