version: '3.8'
services:
  database-mext-mysql:
    container_name: database-mext-mysql
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT}:${MYSQL_PORT}
    expose:
      - ${MYSQL_PORT}
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - my-network
  mext-back:
    container_name: mext-back
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      MYSQL_HOST: host.docker.internal
    command: sh -c "node ace migration:run"
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - database-mext-mysql
    networks:
      - my-network
    

  mext_redis:
    image: redis:alpine
    restart: always
    env_file:
      - .env
    ports:
      - '6379:6379'
    networks:
      - my-network
      
volumes:
  my-db:
    driver: local

networks:
  my-network:
    driver: bridge