# version: 2.1
# orbs:
#   heroku: circleci/heroku@0.0.10
# workflows:
#   heroku_deploy:
#     jobs:
#       - heroku/deploy-via-git
version: 2.1

jobs:
  ci:
    docker:
      - image: circleci/node:14.5.0-browsers
    environment:
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DB_NAME: mext
      MYSQL_HOST: localhost
      MYSQL_PORT: 3306
      DB_CONNECTION: mysql
    services:
      - name: mysql-master
        image: mysql:5.7
        ports:
          - 3306:3306
        environment:
          MYSQL_DATABASE: $MYSQL_DB_NAME
          MYSQL_USER: $MYSQL_USER
          MYSQL_PASSWORD: $MYSQL_PASSWORD
          MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
        healthcheck:
          test: ["CMD", "mysqladmin", "ping"]
          interval: 10s
          timeout: 5s
          retries: 3
    steps:
      - checkout
      - run:
          name: Install node_modules
          command: npm install
      - run:
          name: Migrate db tables
          command: node ace migration:run
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build project
          command: npm run build

workflows:
  version: 2
  build:
    jobs:
      - ci
