name: Mext server CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypassword
  MYSQL_DB_NAME: mext
  MYSQL_HOST: localhost
  MYSQL_PORT: 3306
  DB_CONNECTION: mysql

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Use Node.js version 16
       uses: actions/setup-node@v2
       with:
         node-version: '16'
     - name: Set up MySQL
       run: |
        sudo apt-get install mysql-server=5.7.*
        sudo service mysql start
        mysql -h ${{ env.MYSQL_HOST }} -P ${{ env.MYSQL_PORT }} -u root -e "CREATE USER '${{ env.MYSQL_USER }}'@'localhost' IDENTIFIED BY '${{ env.MYSQL_PASSWORD }}';"
        mysql -h ${{ env.MYSQL_HOST }} -P ${{ env.MYSQL_PORT }} -u root -e "CREATE DATABASE ${{ env.MYSQL_DB_NAME }};"
        mysql -h ${{ env.MYSQL_HOST }} -P ${{ env.MYSQL_PORT }} -u root -e "GRANT ALL PRIVILEGES ON mydb.* TO '${{ env.MYSQL_USER }}'@'localhost';"

     - name: Migrate db tables
       run: node ace migration:run     
     - name: Install node_modules
       run: npm install
     - name: Run tests
       run: npm run test
     - name: build project
       run: npm run build