name: Mext server CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypassword
  MYSQL_DB_NAME: mext
  MYSQL_HOST: localhost
  MYSQL_PORT: 3306
  DB_CONNECTION: mysql

jobs:
  ci:
    runs-on: ubuntu-latest
    # container:
    #   image: node:14.5.0-alpine
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root_password
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Verify MySQL Connection
       run: |
        mysql -h 127.0.0.1 -P 3306 -u test_user --password=test_password -e "SHOW DATABASES;"
     - name: Install node_modules
       run: npm install
     - name: Migrate db tables
       run: node ace migration:run     
     - name: Run tests
       run: npm run test
     - name: build project
       run: npm run build