name: Mext server CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypassword

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - name: Use Node.js version 16
       uses: actions/setup-node@v2
       with:
         node-version: '16'
     - name: Set up MySQL
       run: |
        sudo apt-get install mysql-server
        sudo service mysql start
     - name: Migrate db tables
       run: node ace migration:run     
     - run: npm install
     - run: npm run build