name: Mext server CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  MYSQL_USER: myuser
  MYSQL_PASSWORD: mypassword
  MYSQL_DB_NAME: mext
  MYSQL_HOST: localhost
  MYSQL_PORT: 3306
  DB_CONNECTION: mysql

jobs:
  ci:
    runs-on: ubuntu-latest
    services:
      mysql-master:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DB_NAME }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
     - uses: actions/checkout@v2
     - name: Verify MySQL Connection
       run: |
        mysql -h 127.0.0.1 -P 3306 -u ${{ env.MYSQL_USER }} --password=${{ env.MYSQL_PASSWORD }} -e "SHOW DATABASES;"
    #  - name: Install node_modules
    #    run: npm install
    #  - name: Migrate db tables
    #    run: node ace migration:run     
    #  - name: Run tests
    #    run: npm run test
    #  - name: build project
    #    run: npm run build